import {Outfit} from "next/font/google";
import "./globals.css";
import Provider from "./provider";



export const metadata = {
  title: "Rova | Travel AI",
  description: "Generated by create next app",
};

const outfit=Outfit({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
      <Provider>
        {children}
        </Provider>
        
      </body>
    </html>
  );
}
